#!/bin/bash

cd $(dirname $0)

red() {
    echo -e "\033[1;31m$@\033[0m"
}

green() {
    echo -e "\033[1;32m$@\033[0m"
}

blue() {
    echo -e "\033[1;34m$@\033[0m"
}

green "Install vundle"
git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim

green "Clone Mytools"
git clone https://github.com/jiangjizhong/mytools.git ~/.mytools

link_to(){
    local src=$1
    local symbol=$2
    green "Create link $symbol --> $src"
    if [ -e "$symbol" ]; then
        red "$symbol exists. Will be move to $symbol.old"
        dir=$(dirname $symbol)
        mv $symbol $dir/$symbol.old
    fi
    ln -s $src $symbol
}

link_to ~/.mytools/vim/vimrc ~/.vimrc
link_to ~/.mytools/tmux/tmux.conf ~/.tmux.conf

green "Finish."

