#!/bin/bash

cd $(dirname $0)

red()
{
        echo -e "\033[1;31m$@\033[0m"
}

green()
{
        echo -e "\033[1;32m$@\033[0m"
}

blue()
{
        echo -e "\033[1;34m$@\033[0m"
}

green "Install vundle"
git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim

green "Clone Mytools"
git clone https://github.com/jiangjizhong/mytools.git

green "Create link"
vimrc=~/.vimrc
if [ -f $vimrc ]; then
    red "$vimrc exists. Will be move to $vimrc.old"
    mv $vimrc ${vimrc}.old
fi

ln -s vim/vimrc $vimrc
greend "Finish."

