#!/bin/bash

set -e
cd $(dirname $0)

red() {
    echo -e "\033[1;31m$@\033[0m"
}

green() {
    echo -e "\033[1;32m$@\033[0m"
}

blue() {
    echo -e "\033[1;34m$@\033[0m"
}

green "Install vim-plug"
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

green "Clone Mytools"
git clone https://github.com/jiangjizhong/mytools.git ~/.mytools

link_to(){
    local src=$1
    local symbol=$2
    green "Create link $symbol --> $src"
    if [ -e "$symbol" ]; then
        red "$symbol exists. Will be move to $symbol.old"
        mv $symbol $symbol.old
    fi
    ln -s $src $symbol
}

link_to ~/.mytools/vim/vimrc ~/.vimrc
link_to ~/.mytools/tmux/tmux.conf ~/.tmux.conf

green "Finish."

