"vundle
set nocompatible              " be iMproved
filetype off                  " required!

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'Markdown'
Plugin 'Solarized'
Plugin 'ctrlp.vim'
Plugin 'The-NERD-tree'
Plugin 'tComment'
Plugin 'JSON.vim'
Plugin 'fatih/vim-go'
Plugin 'yaml.vim'

call vundle#end()
filetype plugin indent on

"tags

"color and font
if has("gui_running")
    set background=dark
    colorscheme solarized
    set guifont=Monaco:h15
else
    set background=dark
    colorscheme solarized
endif

"syntax

if has("autocmd")
    filetype plugin on
    augroup te
        autocmd BufRead,BufNewFile *.te set filetype=te
        autocmd BufRead,BufNewFile *.if set filetype=te
    augroup END
endif

set hlsearch
set incsearch
set number
set autoindent
set smartindent
set showcmd
set ruler

syntax on
set smarttab
set tabstop=4
set shiftwidth=4
set expandtab
set encoding=utf-8
set fileencodings=utf-8,gbk,ucs-bom,cp936,iso-8859-1

set guioptions-=m
set guioptions-=T
set guioptions-=L 

set vb t_vb=

"clang
let g:clang_complete_auto = 1
let g:clang_use_library = 1
let g:clang_debug = 1

"tag list
let Tlist_Show_One_File=1
let Tlist_Exit_OnlyWindow=1

let g:NERDTreeChDirMode       = 2
let g:ctrlp_working_path_mode = 'rw'


" map
nnoremap <Leader>nt :NERDTree<CR>
nnoremap <Leader>p :set paste<CR>
autocmd BufRead,BufNewFile *.json nnoremap <Leader>j :%!python -m json.tool<CR>

" split switch
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

set backspace=indent,eol,start


