"vundle
set nocompatible              " be iMproved
filetype off                  " required!

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'vundle'
Bundle 'Solarized'
Bundle 'Markdown'
Bundle 'ctrlp.vim'
Bundle 'The-NERD-tree'
Bundle 'tComment'
Bundle 'xml.vim'
Bundle 'taglist.vim'

filetype plugin indent on

"tags

"color and font
if has("gui_running")
    set bg=dark
    colorscheme solarized
    set guifont=Droid\ Sans\ Mono\ 11
else
    colorscheme default
endif

"syntax

if has("autocmd")
    filetype plugin on
    augroup te
        autocmd BufRead,BufNewFile *.te set filetype=te
        autocmd BufRead,BufNewFile *.if set filetype=te
    augroup END
endif

set hlsearch
set incsearch
set number
set autoindent
set smartindent
set showcmd

set smarttab
set tabstop=4
set shiftwidth=4
set expandtab
set fileencodings=utf-8,gbk,ucs-bom,cp936,iso-8859-1

set guioptions-=m
set guioptions-=T
set guioptions-=L 

"clang
let g:clang_complete_auto = 1
let g:clang_use_library = 1
let g:clang_debug = 1

"tag list
let Tlist_Show_One_File=1
let Tlist_Exit_OnlyWindow=1

" map
nnoremap <Leader>nt :NERDTree<CR>
inoremap { {}<ESC>i<CR><ESC>O
autocmd BufRead,BufNewFile *.json nnoremap <Leader>j :%!python -m json.tool<CR>

